# Generated by Django 5.0.4 on 2024-04-26 09:54

import menu_cart.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='toppings',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='toppings',
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[menu_cart.validators.validate_non_negative]),
        ),
        migrations.DeleteModel(
            name='Topping',
        ),
    ]
