# Generated by Django 5.0.4 on 2024-04-26 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_cart', '0003_topping_alter_menuitem_price_menuitem_toppings'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='toppings',
            field=models.ManyToManyField(blank=True, to='menu_cart.topping'),
        ),
    ]
