# Generated by Django 5.0.4 on 2024-04-26 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_cart', '0004_cartitem_toppings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='toppings',
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
    ]
