# Generated by Django 5.0.4 on 2024-04-30 19:20

import cloudinary.models
import menu_cart.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_cart', '0005_remove_menuitem_toppings_alter_cartitem_subtotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[menu_cart.validators.validate_non_negative]),
        ),
    ]
