# Generated by Django 5.0.4 on 2024-04-26 09:03

import django.db.models.deletion
import index.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PizzaUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=17, validators=[index.validators.validate_customer_phone_number])),
                ('street_address', models.CharField(max_length=100, validators=[index.validators.validate_customer_street_address])),
                ('city', models.CharField(blank=True, max_length=50, validators=[index.validators.validate_customer_city])),
                ('zip_code', models.CharField(blank=True, max_length=10, validators=[index.validators.validate_customer_zip_code])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
