# Generated by Django 5.0.4 on 2024-05-05 12:18

import index.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_newslettersubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('phone_number', models.CharField(max_length=17, validators=[index.validators.validate_customer_phone_number])),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(max_length=350)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
